### ISSUE TITLE
Some code review

### ISSUE THREAD

**Issue by Mark-H** [poconosewandvac/Commerce_GuestOrder#2]
Nice work on this Tony.

I've looked through the code and have a couple of comments. Feel free to incorporate, or ignore, totally up to you!

https://github.com/poconosewandvac/Commerce_GuestOrder/blob/7f5c735aced6f58d04571f9c1636fbee80d8ba62/core/components/commerce_guestorder/elements/snippets/snippet.guestorder.php#L26

`isset($order)` is always going to be true because `$order` is defined on line 5. I'd probably typecast with `(int)` on line 5, and check `if ($order > 0)`.

Code style wise it's also nice to "return early". Right now line 26-163 (that's almost the entire snippet) are inside an `if` block. That adds mental complexity. 

If you change the logic around, you could do something like this instead of the condition on line 26:

```` php
if ($order < 1) {
    // The form chunk to display when an order is not set
    return $modx->getChunk($formTpl);
}
// do the rest
````

https://github.com/poconosewandvac/Commerce_GuestOrder/blob/7f5c735aced6f58d04571f9c1636fbee80d8ba62/core/components/commerce_guestorder/elements/snippets/snippet.guestorder.php#L64

The secret is checked after loading the order here. You could off-load this to the server, and simplify your error handling, by adding the secret to the $orderQuery before line 57. For example:

```` php
    // Build the order query, looking for only guest orders for inputted ID
    $orderQuery = $modx->newQuery('comOrder');
    $orderQuery->where([
        'id' => $order,
        'user' => 0,
        'test' => $commerce->isTestMode(),
        'class_key:IN' => $allowedClasses
    ]);
    if ($useSecret && !empty($secret)) {
        $orderQuery->where([
             'secret' => $secret
        ]);
    }

    $order = $modx->getObject('comOrder', $orderQuery);
````

That way, you will not get the order object if the secret doesn't match.

You'd want to make sure that you properly check when the secret is used and when the address-based is used. I'd almost recommend letting $useSecret alone be the decider of that; that way if users don't provide a secret but useSecret is on, they don't get to see the order either. 

The way you're handling order addresses on line 69-100 I'd recommend switching to use the provided APIs on the order. Think `$billing = $order->getBillingAddress()` and `$shipping = $order->getShippingAddress()` and using those objects instead of fetching addresses separately. You could do a `switch` on the `$addressType` to determine which addresses to check. 

(As an aside, with the option "both", you probably can't get the check to work if they entered, say, a different zip for shipping and billing, because it wont match one or the other. Might be nice if it would support a match on either, but that'd also require rewriting that logic)

**Comment by tonyklapatch** [comment]
Thanks for the review Mark, implemented the changes.
